name: appolifab
favicon: null
layout_spectrum: 0.48445174330845475
typography_spectrum: 0.7257102488074452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6486587529070675
  lightness: 0.3794053809251636
  saturation: 0.6618633912876248
  rhythmicContrast: 0.25944470660761
purpose: []
